name: pagos-a
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres.gbxuojquibukppijatpv:0PdVadsLIfzGJ32r@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    external: true
