name: pagos-a
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-csmmu71u0jms73fq3550-a.oregon-postgres.render.com/payment_module?sslmode=require&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    external: true