name: pagos-a
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      DB_HOST: aws-0-us-west-1.pooler.supabase.com
      DB_PORT: 6543
      DB_NAME: postgres
      DB_USER: postgres.gbxuojquibukppijatpv
      DB_PASSWORD: 0PdVadsLIfzGJ32r
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    external: true
