name: pagos-a
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    external: true