name: pagos-a
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/payment_module
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - pagos-a-db
    networks:
      - my_bridge_network

  pagos-a-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: payment_module
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5132:5132"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    external: true

volumes:
  postgres_data:
