name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  # Test's job
  tests:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: juan_payment
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Unit Tests
        env:
          POSTGRES_URL: jdbc:postgresql://localhost:5432/juan_payment
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        run: mvn -B test

      - name: Run Integration Tests
        env:
          POSTGRES_URL: jdbc:postgresql://localhost:5432/juan_payment
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        run: mvn verify -P integration-tests

  # Sonar's Job
  sonar:
    needs: tests
    name: SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Analyze with SonarCloud
        run: mvn -B verify sonar:sonar -Dspring.datasource.url= -Dspring.datasource.username= -Dspring.datasource.password= -Dspring.jpa.hibernate.ddl-auto=none -Dsonar.projectKey=mono789_Flight-Payment -Dsonar.organization=mono789 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
